### ISSUE TITLE
Secure TLS-Connection for new MP-SPDZ Version

### ISSUE THREAD

**Issue by kindlich** [carbynestack/ephemeral#22]
In #15, the MP-SPDZ Version is changed to `v0.2.8` which introduces TLS-secured communication between MP-SPDZ Clients (=ephemeral) and the MP-SPDZ Process.

The way the PR adds this is really rudimentary and insecure (e.g. the option `InsecureSkipVerify` is set to bypass certificate validation).

```go
	tlsConfig := &tls.Config{
		Certificates:       []tls.Certificate{cert},
		InsecureSkipVerify: true,
	}
```

We will need to think about some points regarding the TLS connection:
- Who will create certificates (and re-created them when expired)?  
  Types of connections
    - Ephemeral <-> MP-SPDZ Process (for transmitting secret shares/results)
    - Cross-Cloud MP-SPDZ instances (for computation)
- Will we continue using self-signed certificates or have a way to provide certifactes signed by CAs?
- Can we provide certificate using e.g. K8s Secrets instead of baking them into the base-image (do some parts of our infrastructure like Istio/Knative already provide some functionality for this here?)

**Comment by strieflin** [comment]
As [discussed on Discord](https://discord.com/channels/938353101147086870/960758450009292810/963050848114602034), the way to go is to make TLS channels optional in upstream MP-SPDZ and have authenticated channels implemented via Istio mechanisms.

**Comment by strieflin** [comment]
TLS has been switched off completely in #15 for both client/engine and engine/engine channels as it is not required in our setting.
