### ISSUE TITLE
Ensure that client supports any number of virtual cloud providers

### ISSUE THREAD

**Issue by strieflin** [carbynestack/ephemeral#24]
The ephemeral client uses Java Parallel Streams (JPS) to interact with the virtual cloud providers (VCPs). By default JPS allocates `n` threads on a `n` core machine. As the HTTP calls are blocking, this results in a timeout on a system with less cores than the number of VCPs as the distributed execution in the backend will only kick-off after all VCPs have received an invocation request.

**Comment by grafjo** [comment]
> 

@strieflin we can reproduce this behavior in the wild with small sized virtual machines - e.g. 2 cpu cores.

Varv Future is using [ForkJoinPool](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ForkJoinPool.html?is-external=true#commonPool--) and that one is configured by the available processors / cpu cores

"For applications that require separate or custom pools, a ForkJoinPool may be constructed with a given target parallelism level; by default, equal to the number of available processors.

**Comment by kindlich** [comment]
Do we need similar changes in Amphora/Castor?
- I think Castor should be fine, since it does not upload/activate tuples concurrently.
- For the Amphora Client, uploading Secrets and retrieving/unveiling Secrets may need another look?

**Comment by strieflin** [comment]
> Do we need similar changes in Amphora/Castor?
> 
>     * I think Castor should be fine, since it does not upload/activate tuples concurrently.
> 
>     * For the Amphora Client, uploading Secrets and retrieving/unveiling Secrets may need another look?

Added an issued to verify Amphora works as expected (see carbynestack/amphora#32).
